.github/zephyr.yml: add a temporary submodules/west consistency check
Real-world experience has proved again that big READMEs are not enough,
not even when they're only a couple lines away as the one added in
commit 8fd351ea9aa6 ("west.yml: add warning to keep git submodules in
sync"). Only some failure / red color stand a chance.

It also seems some people rarely use "git status". This was discovered
in commit d9eb16aa6655 ("cmake: add warning when git submodule changes
are found") but is still surprising.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

diff --git a/.github/workflows/zephyr.yml b/.github/workflows/zephyr.yml
--- a/.github/workflows/zephyr.yml
+++ b/.github/workflows/zephyr.yml
@@ -39,6 +39,25 @@ jobs:
           west init -l
           west update --fetch-opt=--filter=tree:0
 
+      # Temporary check until we change west.yml and stop nesting rimage
+      # and tomlc99 inside sof which will cleanly separate them from
+      # XTOS submodules and... temporarily break every CI, which is why
+      # it hasn't been done yet.
+      - name: git submodules consistency
+        run: |
+
+          cd workspace/sof
+          git submodule update --init --recursive
+
+          west update
+          if git status --porcelain=v2 | grep ^ ; then
+             git status
+             echo 'FAIL: inconsistency between git submodules and west.yml!'
+             echo 'See rimage comment in west.yml.'
+             echo 'Always use "git status"'
+             exit 1
+          fi
+
   build-linux:
     runs-on: ubuntu-20.04
     strategy:
